DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.contrib.auth.views import LoginView, LogoutView

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include # лаба 6
from django.contrib import admin # лаба 6
admin.autodiscover() # лаба 6

from django.conf.urls.static import static #лаба 10
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #лаба 10
from django.conf import settings #лаба 10
from django.views.generic import RedirectView

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^pool$', app.views.pool, name='pool'),
    url(r'^blog', app.views.blog, name='blog'), # лаба 8
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'), # лаба 8
    url(r'^newpost$', app.views.newpost, name='newpost'), # лаба 10
    url(r'^videopost$',app.views.videopost, name='videopost'), # лаба 10
    url(r'^registration$', app.views.registration, name='registration'), # лаба 6
    url(r'^developers$', app.views.developers, name='developers'),# new
    url(r'^catalog$', app.views.catalog, name='catalog'), # new1
    url(r'^basket$', app.views.basket, name='basket'),
    url(r'^(?P<parametr1>\d+)', app.views.delete, name='delete'), # new1
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Вход',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)), # лаба 6
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #лаба 10
urlpatterns += staticfiles_urlpatterns() #лаба 10

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models # Лаба 9
from .models import Comment  # Лаба 9
from .models import Blog #лаба 10
from .models import Catalog #New

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class Support(forms.Form):
        name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
        city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
        gender = forms.ChoiceField(label='Ваш пол',
                                  choices=[('1','Мужской'),('2','Женский')],
                                  widget=forms.RadioSelect, initial=1)
        face = forms.ChoiceField(label='Вы являетесь', 
                                     choices=(('1','индивидуальным предпринимателем'),
                                     ('2','физическим лицом'),
                                     ('3','юридическим лицом'),
                                     ('4','организацией')), initial=1)
        email = forms.EmailField(label='Ваш e-mail', min_length=7)
        message = forms.CharField(label='Текст обращения', widget=forms.Textarea(attrs={'rows':12, 'cols':20}))

class CommentForm (forms.ModelForm): # Лаба 9 v
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text 
        #author будет автоматически выбран в зависимости от авторизованного пользователя
        # date автоматически добавляется в момент создания записи
        
        # лаба 10 v

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description','content','image',)
        labels = {'title':"Заголовок",'description':"Краткое содержание",'content':"Полное содержание",'image':"Изображение"}
        # лаба 10 ^

class CatalogForm(forms.ModelForm):
    class Meta:
        model = Catalog # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "",} # метка к полю формы text

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Наша компания занимается разработкой десктопного программного обеспечения, созданием и настройкой сайтов.</p>
<h3>Наши продукты:</h3>
<p><a href="https://img.imgsmail.ru/cloud/css/build/cloudweb-11571-72-2-1.202011181831/main.css">Программа для рассчёта технологического процесса</a></p>
<p><a href="https://cloud.mail.ru/public/5Hyy/wfBw5rTLW">Программа для решения задач линейного программирования симплексным методом</a></p>
<p><a href="https://cloud.mail.ru/public/5HFg/87dhVbHo1">Программа удалённого управления ПК</a></p>
<p><a href="http://91.240.87.89">Сайт для нормализации адресов</a></p>
{% endblock %}

app/templates/app/basket.html
{% extends "app/layout.html" %} <!-- New1 -->
{% block content %}
{% if user.is_authenticated %}  <!--  лаба 9 v -->
<h3>Заказанные услуги:</h3>
<form method="POST" >{% csrf_token %} {# защита от атак CSRF #}
</form>
{% else %}
<h3> Для добавления своего заказа, пожалуйста, авторизуйтесь </h3>
{% endif %} 
{% for catalog in zakaz %}
<hr/>
<h7 class="catalog-date"> Дата заказа:{{catalog.date}} </h7>
<h5 class="catalog-author">Заказчик: {{catalog.author}} </h5>
<p class="catalog-text"> {{catalog.text|linebreaksbr}} </p>
<p class="catalog-status"> Статус заказа: {{catalog.status}} </p>
<p><a class="btn btn-default" href="{% url 'delete' parametr1=catalog.id %}"> Удалить </a> </p>
{% endfor %} <!--  лаба 9 ^ -->
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %} <!-- файл добвлен в лабе 8 --> 
{% block content %}
<h2>{{ title }}</h2>
{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %} <!-- файл добвлен в лабе 8 -->
{% block content %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %} <!-- лаба 10 v -->
    <img src="{{ post_1.image.url }}" alt="Картинка" width="600" height="400"/>
{% endif %} <!-- лаба 10 ^ -->
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам #}
{% if user.is_authenticated %}  <!--  лаба 9 v -->
<h3>Добавить комментарий</h3>
<form method="POST" >{% csrf_token %} {# защита от атак CSRF #}
<div>
{{form.as_p}}
<button type="submit" class="save btn btn-default" > Отправить </button>
</div>
</form>
{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %} 
{% for comment in comments %}
<hr/>
<h7 class="comment-date"> {{comment.date}} </h7>
<h5 class="comment-author"> {{comment.author}} </h5>
<p class="comment-text"> {{comment.text|linebreaksbr}} </p>
{% endfor %} <!--  лаба 9 ^ -->
<p><a href="{% url 'blog' %}"> Назад </a></p>
{% endblock %}

app/templates/app/catalog.html
{% extends "app/layout.html" %} <!-- New1 -->
{% block content %}
{% if user.is_authenticated %}  <!--  лаба 9 v -->
<h3>Описание услуги:</h3>
<form method="POST" >{% csrf_token %} {# защита от атак CSRF #}
<div class="testee">
    {{form.as_p}}
<button type="submit" class="save btn btn-default" > Добавить </button>
</div>
</form>
{% endif %} 
{% endblock %}

app/templates/app/developers.html
{% extends "app/layout.html" %}

{% block content %}
    <content>
        {% load staticfiles %}
    </content>
    <h2>Наши разработчики</h2>
    <a class="btn-dlinks-default" href ="https://vk.com/greenapelsin" target="_blank"> <img src="{% static 'app/content/Никита.png' %}" alt="Лимаренко Никита"/></a> 
        <p style="margin:15px 0 0 0;">Лимаренко Никита</p>
        <p>Full-stack разработчик</p>
    <a class="btn-dlinks-default" href ="https://vk.com/id105596941" target="_blank"> <img src="{% static 'app/content/Тёма.png' %}" alt="Семушин Артём"/></a>
        <p style="margin:15px 0 0 0;">Семушин Артём</p>
        <p>Product-manager</p>
    <a class="btn-dlinks-default" href ="https://vk.com/spacecreator" target="_blank"> <img src="{% static 'app/content/Толя.png' %}" alt="Корейченко Анатолий"/></a>
        <p style="margin:15px 0 0 0;">Корейченко Анатолий</p>
        <p>Frontend-разработчик</p>
    <a class="btn-dlinks-default" href ="https://vk.com/dmit1996" target="_blank"> <img src="{% static 'app/content/я.png' %}" alt="Иванов Дмитрий"/></a>
        <p style="margin:15px 0 0 0;">Иванов Дмитрий</p>
        <p>Backend-разработчик</p>     
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% block content %}
{% load staticfiles %}

<div class="jumbotron">
    <h1>InovTech</h1>
    <p class="lead">InovTech - это компания с многолетним опытом, занимающаяся разработкой десктопного ПО и web-приложений.</p>
    <p><a href="{% url 'links' %}" class="btn btn-primary btn-large">Читать больше &raquo;</a></p>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="back1"></li>

        <li data-target="#myCarousel" data-slide-to="1" class="back1"></li>

        <li data-target="#myCarousel" data-slide-to="2" class="back1"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/NewTechnology.jpg'%} " alt="Первый слайд" class="img-responsive1" />

            <div class="carousel-caption" role="option">

                <p class="text1">

                   Зачастую требуется разработать продукт, отличающийся от других концептульно новыми решениями.

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/Adaptivity.jpg'%}" alt="Второй слайд"  class="img-responsive1" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409" />

            <div class="carousel-caption" role="option">

                <p class="text2">

                   Адаптивность - залог успешного продвижения сайта, поэтому мы разрабатываем сайты под устройства с различными разрешениями экрана.

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/koding.jpg'%} " alt="Третий слайд"  class="img-responsive1" />

            <div class="carousel-caption" role="option">

                <p class="text3">
                    Программи́ст — специалист, занимающийся программированием, то есть созданием компьютерных программ.
                    Жизнь современного человека трудно представить без различных гаджетов, а гаджеты - это в свою очередь устройства, на которых установлено то или иное ПО.

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>О нас</h2>
        <p>
            Наша компания занимается разработкой програмных продуктах на различных языках программирования, под различные операционные системы.
        </p>
        <p><a href="{% url 'about' %}" class="btn btn-default">Читать больше &raquo; </a></p>
    </div>
    <div class="col-md-4">
        <h2>Наши услуги</h2>
        <p>Мы разрабатываем десктопное ПО в таких средах программирования как Visual Studio, Lazrus, PyCharm. Разработка ПО производится на следующих языках программирования: python, C#, Object Pascal, Java.
        В сферу наших услуг входит создание современных сайтов.</p>
        <p><a class="btn btn-default" href="{% url 'links' %}">Читать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Наши разработчики</h2>
        <p> Наши разработчики - это профессионалы своего дела, это люди с многолетним опытом, программисты высшего класса.</p>
        <p><a class="btn btn-default" href="{% url 'developers' %}">Читать больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - InovTech</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="app\static\app\content" href="{% static "favicon.ico" %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a href="/" class="navbar-brand"> <img src="{% static 'app\content\logo.jpg' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a font-size></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'blog' %}">Статьи</a></li> <!-- лаба 8 -->
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    {% if user.is_authenticated %} <!--New1-->
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    {% endif %}
                    {% if user.is_authenticated and not user.is_superuser %} <!--New1-->
                    <li><a href="{% url 'catalog' %}">Заказ услуги</a></li>
                    {% endif %}
                    {% if user.is_superuser %} <!-- лаба 10 v -->
                    <li><a href="{% url 'newpost' %}"> Добавление статьи </a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li> <!-- лаба 10 ^ -->
                </ul>
                {% if user.is_authenticated and not user.is_superuser %} <!--New1-->
                    <a class="navbar-brand" href="{% url 'basket' %}"><img class="basket" src="{% static 'app\content\basket.png' %}" alt="logo" /></a>
                    {% endif %}

                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p class="footer">&copy; {{ year }} <br />
                InovTech company<p>
        </footer>
    </div>

  
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
    <content>
        {% load staticfiles %}
    </content>
    <h2>Информация о средах разработки</h2>
    <div class="dlinks">
    <a class="btn-dlinks-default" href ="https://visualstudio.microsoft.com/ru/vs/features/" target="_blank"> <img src="{% static 'app/content/Visual Studio.png' %}" alt="Logo1"/></a>
    <a class="btn-dlinks-default" href ="https://lazarus-rus.ru/features/" target="_blank"> <img src="{% static 'app/content/Lazarus.png' %}" alt="Logo2"/></a>
    <a class="btn-dlinks-default" href ="https://timeweb.com/ru/community/articles/pycharm-ide-dlya-python-1" target="_blank"> <img src="{% static 'app/content/Pycharm.png' %}" alt="Logo3"/></a>
    </div>
    <h2 style="margin: 150px 0 0 0;">В сферу нашей деятельности входит:</h2>
        <li>Разработка современных сайтов</li>
        <li>Разработка ПО</li>
        <li>Разработка игр</li>
        <li>Доработка ПО и сайтов</li>
        <li>Настройка сайтов</li>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте для входа свой ранее созданный аккаунт или зарегистрируйтесь.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользвателя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вход" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста введите правильный пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/newpost.html
{% extends "app/layout.html" %} <!--лаба 10 (вся страница)-->

{% block content %}


    <h3>Добавить статью</h3>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %} {# обязательная защита от атак CSRF #}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default"> Опубликовать </button>
    </div>
    </form>

{% endblock %}

app/templates/app/pool.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta charset="utf-8" />
    <title></title>

</head>

<body class="style-anket">
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
    
<br><h2>Пожалуйста заполните информацию о себе для связи.</h2> 
<h2>Информация будет использована только для связи с Вами.</h2><br>
 <div>
    <form method="POST">
    {% csrf_token %}
        <label for="{{ form.name.id_for_label }}" >{{ form.name.label }}: </label>
         {{ form.name }}<br><br>
        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
         {{ form.city }}<br>
        <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
         {{ form.gender }}<br>
        <label for="{{ form.face.id_for_label }}">{{ form.face.label }}:</label>
         {{ form.face }}<br><br>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
         {{ form.email }}<br><br>
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label><br>
        {{ form.message }}<br><br>
        <input  type="submit" value="Отправить" id="b1">
    </form>

     <script>
            function mouse_in()
            {
                $('#b1').css('background', 'green');
                $('#b1').css('color', 'red');
         }
         function mouse_out()
            {
             $('#b1').css('background', 'white');
             $('#b1').css('color', 'black');
            }
        
          function focus_in()
            {
              $('#id_name').css('background', 'lightgreen');
         }
          function focus_out()
            {
                $('#id_name').css('background', 'white');
         }
          function focus_in1()
            {
              $('#id_city').css('background', 'lightgreen');
         }
          function focus_out1()
            {
                $('#id_city').css('background', 'white');
         }
          function focus_in3()
            {
              $('#id_email').css('background', 'lightgreen');
         }
          function focus_out3()
            {
                $('#id_email').css('background', 'white');
         }
                   function focus_in4()
            {
              $('#id_message').css('background', 'lightgreen');
         }
          function focus_out4()
            {
                $('#id_message').css('background', 'white');
         }
         $('#b1').mouseover(mouse_in);
         $('#b1').mouseout(mouse_out);
         $('#id_name').focus(focus_in);
         $('#id_name').blur(focus_out);
         $('#id_city').focus(focus_in1);
         $('#id_city').blur(focus_out1);
         $('#id_email').focus(focus_in3);
         $('#id_email').blur(focus_out3);
         $('#id_message').focus(focus_in4);
         $('#id_message').blur(focus_out4);
     </script>
</div>
{% else %}
<br><h2>Спасибо за обращение. Ответ придёт на указанный Вами email.</h2>
<h3>Вы сообщили о себе следующее и отправили текст обращения:</h3>
<ul>
    <li><span>Имя: </span> {{ data.name }}</li>
    <li><span>Город: </span> {{ data.city }}</li>
    <li><span>Пол: </span> {{ data.gender }}</li>
    <li><span>Вы являетесь </span> {{ data.face }}</li>
    <li><span>Ваш e-mail:</span> {{ data.email }} </li>
    <li><span>Текст обращения:</span>{{ data.message }}</li>
</ul>
{% endif %}
{% endblock %}
</body>
</html>

app/templates/app/registration.html
{% extends "app/layout.html" %} <!--лаба 6 весь файл--> 
{% block content %}
<h2>Регистрация пользователя</h2>
<form method="POST" > {% csrf_token %}
<div>
{{ regform.as_p}}
<button type="submit" class="save btn btn-default" > Зарегистрировать </button>
</div>
</form>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<div>
    <h1>Информация о нашей компании</h1>
    <video src="/media/promoA.mp4" controls="controls" controlsList="nodownload" width="1200" height="600" poster="/media/zastavka.jpg"></video>
</div>
<br/>
<div>
    <h1>Пример разработки игры змейка на python</h1>
<video src="/media/demo.mp4" controls="controls" width="1200" height="600" poster="/media/zastavka1.jpg"></video>
</div>

{% endblock %}